apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-169883287
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-169883287
    app.kubernetes.io/part-of: test-app-169883287
  name: java-quarkus-169883287
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-169883287
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-169883287
    spec:
      containers:
      - image: quay.io/hacdev/ai0n1et0-tenant/test-app-169883287/java-quarkus-169883287@sha256:2d89e41b4c85ce83628ff4269da738cca5852315b129b5ab3ac621dc7b830351
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
