apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: java-quarkus-169883287
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/hacdev/ai0n1et0-tenant/test-app-169883287/java-quarkus-169883287@sha256:2d89e41b4c85ce83628ff4269da738cca5852315b129b5ab3ac621dc7b830351
        name: my-java-quarkus
        resources: {}
status: {}
